### ISSUE TITLE
NullPointerException in MockClient

### ISSUE THREAD

**Issue by sulakm** [Kong/unirest-java#475]
**Describe the bug**
NullPointerException occures in MockClient if both path is body expectations are specified and path is not fullfilled.

**To Reproduce**
MockClient mock = MockClient.register();
mock.expect(HttpMethod.POST, "myurl").body("test").thenReturn().withStatus(200);
mock.verifyAll();

**Proposed fix**
Please change the condition from `expectedBody != null` to `expectedBodyStatus != null` on the line in the link below:
https://github.com/Kong/unirest-java/blob/ad1a81de55ce9423e5a44dfad3f35fc6de56ae17/unirest-mocks/src/main/java/kong/unirest/Invocation.java#L185
It makes more sense to test the reference you are using for method invocation.
This reference is only set if the body is being evaluated.
<pre>
  if(expectedBodyStatus != null){
    sb.append("Body:\n");
    sb.append("\t" + expectedBodyStatus.getDescription()); 
</pre>

**Comment by sulakm** [comment]
Also it seems like the method in expect(HttpMethod, path) is ignored.
I am not sure if it is a bug or intended feature.

I have specified PUT like this `mockClient.expect(HttpMethod.PUT, "some url").thenReturn().withStatus(200);`
mockClient.verifyAll() was satisfied even though only POST method was sent.

**Comment by ryber** [comment]
this is resolved in the most recent releases

**Comment by sulakm** [comment]
@ryber Many thanks for fixing null expectedBodyStatus.
Can you please also add parethenses on [this line](https://github.com/Kong/unirest-java/blob/b8ab11e459e8ea2594905b9139223f09ff27c2ec/unirest-mocks/src/main/java/kong/unirest/Routes.java#L61) as sugested in [comment above](https://github.com/Kong/unirest-java/issues/475#issuecomment-1598092943) ? It is still missing in the latest revision.
